# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/erpc.yaml.j2

erpc:
  fullnameOverride: erpc
  image:
    repository: docker.ethquokkaops.io/gh/erpc/erpc
    tag: 0.0.35
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: rpc.pectra-devnet-5.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  config: |
    logLevel: info

    database:
      evmJsonRpcCache:
        connectors:
          - id: memory-cache
            driver: memory # Refer to "memory" driver docs below
            memory:
              maxItems: 100000
        policies:
          # Cache all methods with finalized data including empty responses
          - network: "*"
            method: "*"
            finality: finalized
            empty: allow
            connector: memory-cache
            ttl: 0
          # Cache unfinalized data only for 5 seconds (getLogs of a recent block) except empty responses
          - network: "*"
            method: "*"
            finality: unfinalized
            empty: ignore
            connector: memory-cache
            ttl: 5s
          # Cache unknown finalization data (eth_trace*) only for 10 seconds
          - network: "*"
            method: "*"
            finality: unknown
            empty: ignore
            connector: memory-cache
            ttl: 10s
          # Cache realtime data only for 2 seconds (eth_blockNumber, eth_gasPrice, etc) to reduce costs yet fresh enough data
          - network: "*"
            method: "*"
            finality: realtime
            empty: ignore
            connector: memory-cache
            ttl: 2s
            
    server:
      httpHostV4: "0.0.0.0"
      listenV6: true
      httpHostV6: "[::]"
      httpPort: 4000
      aliasing:
        rules:
          - matchDomain: "*"
            serveProject: "main"
            serveArchitecture: "evm"
            serveChain: "7088110746"

    metrics:
      enabled: true
      hostV4: "0.0.0.0"
      hostV6: "[::]"
      port: 4001

    projects:
      - id: main
        networks:
          - architecture: evm
            evm:
              chainId: 7088110746
        cors:
          allowedOrigins:
            #- "https://*.ethpandaops.io"
            - "*"
          allowedMethods: 
            - "GET"
            - "POST"
            - "OPTIONS"
          allowedHeaders:
            - "Content-Type"
        upstreamDefaults:
          allowMethods:
            - "eth_blockNumber"
            - "eth_call"
            - "eth_chainId"
            - "eth_estimateGas"
            - "eth_feeHistory"
            - "eth_gasPrice"
            - "eth_getBalance"
            - "eth_getBlockByHash"
            - "eth_getBlockByNumber"
            - "eth_getBlockReceipts"
            - "eth_getBlockTransactionCountByHash"
            - "eth_getBlockTransactionCountByNumber"
            - "eth_getCode"
            - "eth_getFilterChanges"
            - "eth_getLogs"
            - "eth_getStorageAt"
            - "eth_getTransactionByBlockHashAndIndex"
            - "eth_getTransactionByBlockNumberAndIndex"
            - "eth_getTransactionByHash"
            - "eth_getTransactionCount"
            #- "eth_getTransactionReceipt" tmp disable
            - "eth_newBlockFilter"
            - "eth_newPendingTransactionFilter"
            - "eth_maxPriorityFeePerGas"
            - "eth_sendRawTransaction"
            - "eth_subscribe"
            - "eth_syncing"
            - "eth_uninstallFilter"
            - "eth_unsubscribe"
            - "net_listening"
            - "net_version"
            - "rpc_modules"
            - "web3_clientVersion"
            - "debug_getRawReceipts"
            - "debug_traceBlock"
            - "trace_transaction"
            - "trace_block"
        upstreams:
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.bootnode-1.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.grandine-geth-1.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.grandine-nethermind-1.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lighthouse-geth-1.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lighthouse-geth-2.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lighthouse-geth-3.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lighthouse-geth-4.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lighthouse-geth-5.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lighthouse-nethermind-1.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lodestar-geth-1.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lodestar-nethermind-1.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.nimbus-geth-1.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.nimbus-nethermind-1.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.prysm-geth-1.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.prysm-geth-2.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.prysm-geth-3.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.prysm-geth-4.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.prysm-geth-5.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.prysm-nethermind-1.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.teku-geth-1.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.teku-geth-2.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.teku-geth-3.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.teku-geth-4.pectra-devnet-5.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.teku-nethermind-1.pectra-devnet-5.ethpandaops.io
