default_ethereum_client_images:
### Consensus layer clients
  lighthouse: ethpandaops/lighthouse:pawan-electra-alpha7-0dd215c
  lodestar: ethpandaops/lodestar:devnet-4-1531b19
  nimbus: ethpandaops/nimbus-eth2:rRH-1f12f14
  prysm: ethpandaops/prysm-beacon-chain:develop-4aa5410
  prysm_validator: ethpandaops/prysm-validator:develop-4aa5410
  teku: ethpandaops/teku:master-b22b3d5
  grandine: ethpandaops/grandine:pectra-devnet4-05da9f1
### Execution layer clients
  besu: ethpandaops/besu:pectra-devnet-4-9a317b1
  geth: ethpandaops/geth:lightclient-prague-devnet-4-37035c5
  erigon: thorax/erigon:docker_pectra
  ethereumjs: ethpandaops/ethereumjs:7702-devnet-4-plus-t8ntool-3f3a3cc
  nethermind: ethpandaops/nethermind:pectra_devnet_4-c3827bc
  reth: ethpandaops/reth:onbjerg-devnet-4-3793b90


default_tooling_images:
  xatu_sentry: ethpandaops/xatu:0.0.9-pectra-debian
  ethereum_metrics_exporter: ethpandaops/ethereum-metrics-exporter:latest
  tx_fuzz: ethpandaops/tx-fuzz:pr-56
  forkmon: skylenet/nodemonitor:darkmode
  forky: ethpandaops/forky:latest
  fauceth: skylenet/fauceth:fix_fee_estimation
  powfaucet: pk910/powfaucet:v2-stable
  ethstats: skylenet/ethstats-server:poa-no-geoip
  homepage: ethpandaops/ethereum-testnet-homepage:latest
  checkpointz: ethpandaops/checkpointz:0.0.5-electra-debian
  blockscout: blockscout/blockscout:master
  beacon_metrics_gazer: dapplion/beacon-metrics-gazer:latest
  eth_fauceth: chainflag/eth-faucet:latest
  blobscan: blossomlabs/blobscan:latest
  blobscan_indexer: blossomlabs/blobscan-indexer:latest
  dora: ethpandaops/dora:master-latest
  dugtrio: ethpandaops/dugtrio:latest
  ethereum_genesis_generator: ethpandaops/ethereum-genesis-generator:3.4.0
  tracoor: ethpandaops/tracoor:0.0.25-debian
  ncli: status-im/nimbus-eth2:unstable
  lcli: ethpandaops/lighthouse:unstable-a94b12blo
  zcli: electra
  assertoor: ethpandaops/assertoor:electra-support-latest
