default_ethereum_client_images:
### Consensus layer clients
  lighthouse: ethpandaops/lighthouse:electra-devnet-1-51d51f5
  lodestar: ethpandaops/lodestar:electra-fork-rebasejul30
  nimbus: ethpandaops/nimbus-eth2:unstable-f5d360d
  prysm: gcr.io/prylabs-dev/prysm/beacon-chain:pectra-devnet-2
  prysm_validator: ethpandaops/prysm-validator:develop-9e25026
  teku: ethpandaops/teku:master-2d2d17b
  grandine: ethpandaops/grandine:electra-d61707d
### Execution layer clients
  besu: ethpandaops/besu:main-8523ed0
  geth: ethpandaops/geth:prague-devnet-2-17172a0
  erigon: thorax/erigon:docker_pectra
  ethereumjs: ethpandaops/ethereumjs:master-f9788a1
  nethermind: nethermindeth/nethermind:pectra
  reth: ethpandaops/reth:onbjerg-devnet-2-36bc13d


default_tooling_images:
  xatu_sentry: ethpandaops/xatu:latest
  ethereum_metrics_exporter: ethpandaops/ethereum-metrics-exporter:latest
  tx_fuzz: ethpandaops/tx-fuzz:latest
  forkmon: skylenet/nodemonitor:darkmode
  forky: ethpandaops/forky:latest
  fauceth: skylenet/fauceth:fix_fee_estimation
  powfaucet: pk910/powfaucet:v2-stable
  ethstats: skylenet/ethstats-server:poa-no-geoip
  homepage: ethpandaops/ethereum-testnet-homepage:latest
  checkpointz: ethpandaops/checkpointz:latest
  blockscout: blockscout/blockscout:master
  beacon_metrics_gazer: dapplion/beacon-metrics-gazer:latest
  eth_fauceth: chainflag/eth-faucet:latest
  blobscan: blossomlabs/blobscan:latest
  blobscan_indexer: blossomlabs/blobscan-indexer:latest
  dora: ethpandaops/dora:latest
  dugtrio: ethpandaops/dugtrio:latest
  ethereum_genesis_generator: ethpandaops/ethereum-genesis-generator:3.3.5
  tracoor: ethpandaops/tracoor:0.0.22-debian
  ncli: status-im/nimbus-eth2:unstable
  lcli: sigp/lighthouse:electra-devnet-1
  zcli: electra
  assertoor: ethpandaops/assertoor:electra-support-latest
