# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/config.yaml.j2

network: pectra-devnet-0
chainId: 7011893080

domain: pectra-devnet-0.ethpandaops.io

config:
  enabled: true
  files:
    # Support all files as they appear in the github repo
    - path: /besu.json
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/besu.json
    - path: /bootnode.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/bootnode.txt
    - path: /bootstrap_nodes.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/bootstrap_nodes.txt
    - path: /chainspec.json
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/chainspec.json
    - path: /config.yaml
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/config.yaml
    - path: /deploy_block.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/deploy_block.txt
    - path: /deposit_contract.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/deposit_contract.txt
    - path: /deposit_contract_block.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/deposit_contract_block.txt
    - path: /deposit_contract_block_hash.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/deposit_contract_block_hash.txt
    - path: /genesis.json
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/genesis.json
    - path: /genesis.ssz
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/genesis.ssz
    - path: /parseBeaconState.json
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/parseBeaconState.json
    - path: /trusted_setup.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/trusted_setup.txt
    - path: /trusted_setup.json
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/trusted_setup.json

    # Execution Layer specific redirects
    - path: /el/bootnodes
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/bootnode.txt
    - path: /el/besu.json
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/besu.json
    - path: /el/chainspec.json
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/chainspec.json
    - path: /el/genesis.json
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/genesis.json

    # Consensus Layer specific redirects
    - path: /cl/bootstrap_nodes.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/bootstrap_nodes.txt
    - path: /cl/boot_enr.yaml
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/boot_enr.yaml
    - path: /cl/config.yaml
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/config.yaml
    - path: /cl/genesis.ssz
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/genesis.ssz
    - path: /cl/deploy_block.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/deploy_block.txt
    - path: /cl/deposit_contract.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/deposit_contract.txt
    - path: /cl/deposit_contract_block.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/template-devnets/master/network-configs/pectra-devnet-0/deposit_contract_block.txt

    # Ansible generated ethereum nodes inventory
    - path: /api/v1/nodes/inventory
      upstream: bootnode-1.pectra-devnet-0.ethpandaops.io
      target: /meta/api/v1/inventory.json
    - path: /api/v1/nodes/validator-ranges
      upstream: bootnode-1.pectra-devnet-0.ethpandaops.io
      target: /meta/api/v1/validator-ranges.json
