# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora.yaml.j2

dora:
  fullnameOverride: dora
  image:
    repository: ethpandaops/dora
    tag: electra-support
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: dora.pectra-devnet-0.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  name: pectra-devnet-0
  configPath: "https://config.pectra-devnet-0.ethpandaops.io/cl/config.yaml"
  validatorNamesInventory: "https://config.pectra-devnet-0.ethpandaops.io/api/v1/nodes/validator-ranges"
  proxyCount: 2
  extraEnv:
   - name: FRONTEND_PPROF
     value: "true"
   
  postgresql:
    name: "dora-postgresql"
    fullnameOverride: "dora-postgresql"
  
  endpoints:
  # Rpc
  - url: http://teku-geth-001:5052
    name: rpc-teku-geth-001
    archive: true
    priority: 1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.bootnode-1.pectra-devnet-0.ethpandaops.io
    name: bootnode-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.grandine-besu-1.pectra-devnet-0.ethpandaops.io
    name: grandine-besu-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.grandine-geth-1.pectra-devnet-0.ethpandaops.io
    name: grandine-geth-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.grandine-nethermind-1.pectra-devnet-0.ethpandaops.io
    name: grandine-nethermind-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lighthouse-besu-1.pectra-devnet-0.ethpandaops.io
    name: lighthouse-besu-1
    priority: -1
    archive: true
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lighthouse-ethereumjs-1.pectra-devnet-0.ethpandaops.io
    name: lighthouse-ethereumjs-1
    priority: -1
    archive: true
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lighthouse-geth-1.pectra-devnet-0.ethpandaops.io
    name: lighthouse-geth-1
    priority: -1
    archive: true
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lighthouse-nethermind-1.pectra-devnet-0.ethpandaops.io
    name: lighthouse-nethermind-1
    priority: -1
    archive: true
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lighthouse-reth-1.pectra-devnet-0.ethpandaops.io
    name: lighthouse-reth-1
    priority: -1
    archive: true
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lodestar-geth-1.pectra-devnet-0.ethpandaops.io
    name: lodestar-geth-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.nimbus-geth-1.pectra-devnet-0.ethpandaops.io
    name: nimbus-geth-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.prysm-besu-1.pectra-devnet-0.ethpandaops.io
    name: prysm-besu-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.prysm-geth-1.pectra-devnet-0.ethpandaops.io
    name: prysm-geth-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.prysm-nethermind-1.pectra-devnet-0.ethpandaops.io
    name: prysm-nethermind-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.teku-besu-1.pectra-devnet-0.ethpandaops.io
    name: teku-besu-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.teku-geth-1.pectra-devnet-0.ethpandaops.io
    name: teku-geth-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.teku-nethermind-1.pectra-devnet-0.ethpandaops.io
    name: teku-nethermind-1
    priority: -1
