default_ethereum_client_images:
### Consensus layer clients
  lighthouse: sigp/lighthouse:latest
  lodestar: chainsafe/lodestar:latest
  nimbus: statusim/nimbus-eth2:multiarch-latest
  prysm: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
  prysm_validator: gcr.io/prysmaticlabs/prysm/validator:latest
  teku: consensys/teku:latest
  grandine: ethpandaops/grandine:develop
### Execution layer clients
  besu: hyperledger/besu:latest
  geth: ethereum/client-go:stable
  erigon: thorax/erigon:devel
  ethereumjs: ethpandaops/ethereumjs:master
  nethermind: nethermindeth/nethermind:master
  reth: ethpandaops/reth:main


default_tooling_images:
  xatu_sentry: ethpandaops/xatu:latest
  ethereum_metrics_exporter: ethpandaops/ethereum-metrics-exporter:latest
  tx_fuzz: ethpandaops/tx-fuzz:latest
  forkmon: skylenet/nodemonitor:darkmode
  forky: ethpandaops/forky:latest
  fauceth: skylenet/fauceth:fix_fee_estimation
  powfaucet: pk910/powfaucet:v2-stable
  ethstats: skylenet/ethstats-server:poa-no-geoip
  homepage: ethpandaops/ethereum-testnet-homepage:latest
  checkpointz: ethpandaops/checkpointz:latest
  blockscout: blockscout/blockscout:master
  beacon_metrics_gazer: dapplion/beacon-metrics-gazer:latest
  eth_fauceth: chainflag/eth-faucet:latest
  blobscan: blossomlabs/blobscan:latest
  blobscan_indexer: blossomlabs/blobscan-indexer:latest
  dora: ethpandaops/dora:master
  dugtrio: ethpandaops/dugtrio:latest
  ethereum_genesis_generator: ethpandaops/ethereum-genesis-generator:3.1.5
