- hosts: all, !localhost
  serial: "{{ batch_count | default('100%') }}"
  become: true
  tasks:
    #- name:
    #  ansible.builtin.pause:
    #    prompt: |+
    #      =========================================================
    #                  !!!!!!!!!  WARNING  !!!!!!!!!
    #      =========================================================
    #      You're about to cleanup all data on the following nodes:
    #      {% for host in ansible_play_hosts_all | sort %}
    #        - {{ host }}
    #      {% endfor %}
    #      =========================================================
    #      Are you sure you want to continue? (yes/no)
    #  register: prompt
    - name: Cleanup all data
      #when: prompt.user_input == "yes"
      block:
        - name: Remove eth containers
          community.docker.docker_container:
            name: "{{ item }}"
            state: absent
            timeout: 5
          loop:
            # Execution layer clients
            - "besu"
            - "erigon-init"
            - "erigon"
            - "ethereumjs"
            - "geth-init"
            - "geth"
            - "nethermind"
            - "execution"
            - "execution-init"
            - "nimbusel"
            # Consensus layer clients
            - "lighthouse-validator"
            - "lighthouse"
            - "lodestar-validator"
            - "lodestar"
            - "nimbus"
            - "prysm-validator"
            - "prysm"
            - "teku-validator"
            - "teku"
            - "grandine"
            - "beacon"
            - "validator"
            # Others
            - "ethereum-metrics-exporter"
            - "snooper-engine"
            - "snooper-rpc"
            - "cl-bootnode"
            - "mev-boost"
            - "external-block-builder"
        - name: Remove data dirs
          file:
            state: absent
            path: "{{ item }}"
          loop:
            # Execution layer data
            - /data/besu
            - /data/erigon
            - /data/ethereumjs
            - /data/geth
            - /data/nethermind
            - /data/reth
            - /data/nimbusel
            # Consensus layer data
            - /data/lighthouse
            - /data/lighthouse-validator
            - /data/lodestar
            - /data/lodestar-validator
            - /data/nimbus
            - /data/nimbus-validator
            - /data/prysm
            - /data/prysm-validator
            - /data/teku
            - /data/teku-validator
            - /data/grandine
            - /data/grandine-validator
            # Config files
            - /data/ethereum-network-config
            - /data/execution-auth.secret
            - /data/cl-bootnode
