default_ethereum_client_images:
### Consensus layer clients
  lighthouse: docker.ethquokkaops.io/dh/ethpandaops/lighthouse:unstable-a1b7d61
  lodestar: docker.ethquokkaops.io/dh/ethpandaops/lodestar:unstable-cf23839
  nimbus: docker.ethquokkaops.io/dh/ethpandaops/nimbus-eth2:unstable-67ac6fc
  prysm: docker.ethquokkaops.io/dh/ethpandaops/prysm-beacon-chain:fix-batch-process-pending-deposits-e97788e
  prysm_validator: docker.ethquokkaops.io/dh/ethpandaops/prysm-validator:fix-batch-process-pending-deposits-e97788e
  teku: docker.ethquokkaops.io/dh/ethpandaops/teku:master-28f69d3
  grandine: docker.ethquokkaops.io/dh/ethpandaops/grandine:devnet5-7ba51a4
### Execution layer clients
  besu: docker.ethquokkaops.io/dh/ethpandaops/besu:pectra-devnet-5-fix-c5865e9
  geth: docker.ethquokkaops.io/dh/ethpandaops/geth:prague-devnet-5-f24d6f6
  erigon: docker.ethquokkaops.io/dh/ethpandaops/erigon:pectra5-d6a6601
  ethereumjs: docker.ethquokkaops.io/dh/ethpandaops/ethereumjs:devnet5-excessgas-fix-573f023
  nethermind: docker.ethquokkaops.io/dh/nethermindeth/nethermind:devnet-5-blsfix
  reth: docker.ethquokkaops.io/dh/ethpandaops/reth:main-8a453ba
  nimbusel: docker.ethquokkaops.io/dh/ethpandaops/nimbus-eth1:master-c11f20f

default_tooling_images:
  xatu_sentry: docker.ethquokkaops.io/dh/ethpandaops/xatu:1.0.25-debian
  ethereum_metrics_exporter: docker.ethquokkaops.io/dh/ethpandaops/ethereum-metrics-exporter:latest
  tx_fuzz: docker.ethquokkaops.io/dh/ethpandaops/tx-fuzz:pr-56
  forkmon: docker.ethquokkaops.io/dh/skylenet/nodemonitor:darkmode
  forky: docker.ethquokkaops.io/dh/ethpandaops/forky:latest
  fauceth: docker.ethquokkaops.io/dh/skylenet/fauceth:fix_fee_estimation
  powfaucet: docker.ethquokkaops.io/dh/pk910/powfaucet:v2-stable
  ethstats: docker.ethquokkaops.io/dh/skylenet/ethstats-server:poa-no-geoip
  homepage: docker.ethquokkaops.io/dh/ethpandaops/ethereum-testnet-homepage:latest
  checkpointz: docker.ethquokkaops.io/dh/ethpandaops/checkpointz:0.0.12-electra
  blockscout: docker.ethquokkaops.io/dh/blockscout/blockscout:latest
  blockscout_frontend: docker.ethquokkaops.io/gh/blockscout/frontend:latest
  beacon_metrics_gazer: docker.ethquokkaops.io/dh/dapplion/beacon-metrics-gazer:latest
  eth_fauceth: docker.ethquokkaops.io/dh/chainflag/eth-faucet:latest
  blobscan: docker.ethquokkaops.io/dh/blossomlabs/blobscan:latest
  blobscan_indexer: docker.ethquokkaops.io/dh/blossomlabs/blobscan-indexer:latest
  dora: docker.ethquokkaops.io/dh/ethpandaops/dora:master-latest
  dugtrio: docker.ethquokkaops.io/dh/ethpandaops/dugtrio:latest
  ethereum_genesis_generator: docker.ethquokkaops.io/dh/ethpandaops/ethereum-genesis-generator:3.5.4
  tracoor: docker.ethquokkaops.io/dh/ethpandaops/tracoor:0.0.26-debian
  ncli: docker.ethquokkaops.io/dh/status-im/nimbus-eth2:unstable
  lcli: docker.ethquokkaops.io/dh/ethpandaops/lighthouse:unstable-a94b12blo
  zcli: electra
  assertoor: docker.ethquokkaops.io/dh/ethpandaops/assertoor:master-latest
  erpc: docker.ethquokkaops.io/gh/erpc/erpc:main
  prometheus: docker.ethquokkaops.io/dh/prom/prometheus:v2.40.7
  node_exporter: docker.ethquokkaops.io/dh/prom/node-exporter:v1.5.0
  cl_bootnode: docker.ethquokkaops.io/dh/protolambda/eth2-bootnode:cleanup
  json_rpc_snooper: docker.ethquokkaops.io/dh/ethpandaops/json-rpc-snoop:1.1.0
  nginx_proxy: docker.ethquokkaops.io/dh/nginx:alpine
  nginx_proxy_gen: docker.ethquokkaops.io/dh/nginxproxy/docker-gen
  nginx_proxy_acme: docker.ethquokkaops.io/dh/nginxproxy/acme-companion
  panda_pulse: docker.ethquokkaops.io/dh/ethpandaops/panda-pulse:latest